# Helm values for kube-prometheus-stack
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

alertmanager:
  enabled: false
defaultRules:
  create: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
# Disable all built-in Kubernetes component scrapers (api server, kubelet, etc.)
kubernetesServiceMonitors:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableFeatures:
      - native-histograms
    enableRemoteWriteReceiver: true
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          access: proxy
          orgId: 1
          url: http://kube-prometheus-stack-prometheus.telemetry:9090
          basicAuth: false
          editable: true
          jsonData:
            httpMethod: GET
            exemplarTraceIdDestinations:
              - name: trace_id
                datasourceUid: tempo
        - name: Tempo
          type: tempo
          access: browser
          basicAuth: false
          orgId: 1
          uid: tempo
          url: http://tempo.telemetry.svc.cluster.local:3100
          isDefault: false
          editable: true
        - orgId: 1
          name: Loki
          type: loki
          typeName: Loki
          access: browser
          url: http://loki.telemetry.svc.cluster.local:3100
          basicAuth: false
          isDefault: false
          editable: true
