apiVersion: v1
kind: Service
metadata:
  name: mcp-currency-server
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: mcp-currency-server
    app: mcp-currency-server
spec:
  selector:
    app: mcp-currency-server
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
