apiVersion: agentgateway.demo/v1
kind: Environment
metadata:
  name: local
  description: Local Kubernetes cluster (lok8s)

spec:
  # No infraProfile or dns - purely local cluster
  tls:
    issuer: selfsigned-issuer

  keycloak:
    scheme: http

  domains:
    keycloak: keycloak.keycloak.svc.cluster.local
    grafana: kube-prometheus-stack-grafana.telemetry.svc.cluster.local
    quotaManagement: quota-management.agentgateway-system.svc.cluster.local
    soloUI: solo-enterprise-ui.agentgateway-system.svc.cluster.local
    okta: dev-12345.okta.com
    agentgateway: agentgateway.agentgateway-system.svc.cluster.local
