apiVersion: v1
kind: ServiceAccount
metadata:
  name: m2m-agent
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: m2m-agent
    app: m2m-agent
